---
# - name: "초기 변수 설정"
#   hosts: bootstrap
#   vars_files:
#     - group_vars/all.yml
#   tasks:
#     - name: "clean 변수 확인"
#       debug:
#         var: clean

- name: "fsid 검증"
  hosts: bootstrap
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks: 
    - name: "group_vars/all.yml 파일의 {{ clean.fsid }} 값이 입력되지 않은 경우 실패"
      ansible.builtin.fail: 
        msg: |
          "group_vars/all.yml 파일의 clean.fsid를 입력해주세요. \n
          e.g. cephadm shell -- fsid"
      when: clean.fsid is undefined

- name: "관리 호스트에 키링 존재 여부 확인"
  hosts: bootstrap
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: "/etc/ceph/ceph.client.admin.keyring 확인"
      ansible.builtin.stat:
        path: /etc/ceph/ceph.client.admin.keyring
      register: admin_keyring_stat

    - name: "/etc/ceph/ceph.client.admin.keyring이 없으면 실패"
      ansible.builtin.fail:
        msg: >
          관리 호스트 {{ inventory_hostname }}에 /etc/ceph/ceph.client.admin.keyring이 없습니다.
      when: not admin_keyring_stat.stat.exists | bool

- name: "클러스터 호스트에 cephadm 및 필요한 fsid 존재 여부 확인"
  hosts: all
  become: true
  any_errors_fatal: true
  tasks:
    - name: "cephadm 바이너리 사용 가능 여부 확인"
      ansible.builtin.command: which cephadm
      register: cephadm_exists
      changed_when: false
      failed_when: false

    - name: "cephadm이 사용 불가능하면 실패"
      ansible.builtin.fail:
        msg: |
          {{ inventory_hostname }}에 cephadm 바이너리가 없습니다. 
          클러스터를 삭제하려면 모든 Ceph 호스트에 cephadm이 설치되어 있어야 합니다.
      when: cephadm_exists.rc != 0

    - name: "클러스터 전체에 주어진 fsid 디렉토리 유효성 확인"
      ansible.builtin.stat:
        path: /var/lib/ceph/{{ clean.fsid }}
      register: fsid_exists

    - name: "fsid 디렉토리가 없으면 실패"
      ansible.builtin.fail:
        msg: |
          "{{ inventory_hostname }}에 fsid 디렉토리 '/var/lib/ceph/{{ clean.fsid }}'가 없습니다.\n
          fsid가 올바른지 확인하세요."
      when: not fsid_exists.stat.exists

- name: "클러스터 삭제 유무 확인"
  hosts: bootstrap
  gather_facts: false
  become: false
  tasks:
    - name: "클러스터 삭제 확인 요청"
      pause:
        prompt: |
          [경고] 클러스터 삭제를 진행합니다.
          삭제할 FSID: {{ clean.fsid }}
          ⚠️ 이 작업은 되돌릴 수 없습니다.
          계속 진행하려면 "yes"를 입력하세요.
      register: user_input

    - name: "플레이북 종료"
      fail:
        msg:
          - "❌ 클러스터 삭제가 취소되었습니다."
          - "삭제하려면 다시 실행 후 'yes'를 입력하세요."
      when: user_input.user_input | lower != 'yes'

- name: "cephadm 작업 비활성화"
  hosts: bootstrap
  become: true
  gather_facts: false
  tasks:
    - name: "cephadm 비활성화"
      ansible.builtin.command: "cephadm shell --fsid {{ clean.fsid }} -- ceph mgr module disable cephadm"
      register: cephadm_disable_result
      changed_when: false
      timeout: 120  # 타임아웃

    - name: "타임아웃 발생 시 실패 처리"
      ansible.builtin.fail:
        msg: "cephadm 비활성화 작업이 완료되지 않았습니다. 서버 재시작(reboot) 후 다시 실행해주세요."
      when: cephadm_disable_result.rc == 124  # 타임아웃 시 rc는 124

- name: "클러스터의 모든 호스트에서 Ceph 데몬 및 패키지 삭제"
  hosts: all
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: "Ceph 패키지 제거"
      ansible.builtin.package:
        name: "{{ clean.packages }}"
        state: absent
      register: result
      until: result is succeeded

    - name: "Ceph cluster 삭제 시작"
      debug:
        msg: "Ceph 클러스터 삭제 중... (시간이 다소 걸릴 수 있습니다.)"

    - name: "Ceph cluster 삭제 진행 중..."
      command: cephadm rm-cluster --force --zap-osds --fsid "{{ clean.fsid }}"
      async: 600
      poll: 5
      register: rm_cluster_result

    - name: "Ceph 클러스터 삭제 완료"
      debug:
        msg: "Ceph 클러스터 삭제가 완료되었습니다."