all:
  hosts:
    squid7:
      ansible_host: 192.168.0.121
      cluster_ip: 10.0.3.121
    squid8:
      ansible_host: 192.168.0.122
      cluster_ip: 10.0.3.122
    squid9:
      ansible_host: 192.168.0.123
      cluster_ip: 10.0.3.123