- name: Ceph 상태 확인
  shell: cephadm shell -- ceph -s --format json-pretty
  register: ceph_status
  when: inventory_hostname == ceph.bootstrap_node

- name: Ceph 상태 출력
  debug:
    msg: "{{ ceph_status.stdout | from_json }}"
  when: inventory_hostname == ceph.bootstrap_node

- name: Ceph Dashboard URL 확인
  shell: cephadm shell -- ceph mgr services --format json-pretty
  register: ceph_dashboard_url
  when: inventory_hostname == ceph.bootstrap_node

- name: Ceph Dashboard 접속 정보 출력
  debug:
    msg: "{{ ceph_dashboard_url.stdout | from_json }}"
  when: inventory_hostname == ceph.bootstrap_node

- name: Ceph Dashboard 관리자 계정 정보 확인
  shell: cephadm shell -- ceph dashboard ac-user-show admin --format json-pretty
  register: ceph_dashboard_admin
  when: inventory_hostname == ceph.bootstrap_node

- name: Ceph Dashboard 관리자 계정 상태 출력
  debug:
    msg: "{{ ceph_dashboard_admin.stdout | from_json }}"
  when: inventory_hostname == ceph.bootstrap_node