---
ansible_user: root
ansible_ssh_pass: squid

# 클러스터 배포 관련 설정
ceph:
  mon_ip: 192.168.0.191
  cluster_network: "10.0.4.0/24"
  version: "quay.io/ceph/ceph:v19.2.0"
  cephadm_version: "19.2.0"
  fsid: "fb2a0676-f439-11ef-82d7-080027b7bc18" # FSID 미지정 시 자동 생성  
  dashboard:
    init_password: "squid!@#$"

clean: # 클러스터 삭제시 사용
  fsid: "fb2a0676-f439-11ef-82d7-080027b7bc18"
  dirs:  # 삭제할 디렉토리 목록
    - /etc/ceph
    - /var/lib/ceph
    - /var/log/ceph
  packages:  # 삭제할 패키지 목록
    - ceph
    - ceph-mgr
    - ceph-mon
    - ceph-osd
    - ceph-mds
    - ceph-common

# 배포할 서비스 정의
services:
  # 필수 서비스: Ceph 클러스터의 기본 동작을 위해 반드시 배포해야 함
  mon:
    placement: "3"  # Monitor: 클러스터 상태 관리

  mgr:
    placement: "2"  # Manager: 관리 기능 및 대시보드 제공

  osd:
    #모든 디바이스를 osd로 활성화 하는 경우 devices 입력 안해도됨
    #false인 경우 devices 작성
    all_available_devices: true 
    name: "osd.default"  # Object Storage Daemon: 데이터 저장, 필수
    hosts:
      - "squid4"
      - "squid5"
      - "squid6"
    devices: #osd로 사용할 devices
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/nvme0n1"
      - "/dev/nvme0n2"

  # 선택 서비스: 필요에 따라 배포, 사용하지 않을 경우 빈 리스트([])로 설정 가능  
  # Metadata Server: CephFS(파일 스토리지) 사용 시 필요
  mds:
    - name: "mds.default"
      placement: "3"
      pool:
        metadata: "cephfs_metadata"
        data: "cephfs_data"

  # RADOS Gateway: 객체 스토리지(S3/Swift) 사용 시 필요
  rgw:
    - name: "rgw.default"
      placement: "3"
      pool: "rgw_data"
      realm: 
        name: "realm.default"
        default: true
      zonegroup: 
        name: "zonegroup.default"
        default: true
        master: true
      zone: 
        name: "zone.default"
        master: true
        default: true
      port: 7480
    - name: "rgw.default2"
      placement: "3"
      pool: "rgw_data2"
      realm:
        name: "realm.default2"
      zonegroup:
        name: "zonegroup.default2"
      zone: 
        name: "zone.default2"
      port: 7481 

  # NFS: CephFS 기반 NFS 서버, 파일 스토리지 사용 시 필요 (MDS 의존)
  nfs:
    - name: "nfs.default"
      placement: "3"
      pool: "cephfs_data"

  # RBD Mirror: 블록 스토리지 미러링 사용 시 필요
  rbd_mirror:
    - placement: "3"
      pool: "rbd_pool"

  # iSCSI Gateway: 블록 스토리지를 iSCSI로 제공 시 필요
  iscsi:
    - name: "iscsi.default"
      pool: "iscsi_pool"
      api_user: "iscsi_admin_user"
      api_password: "ceph!@#$"
      placement:
        hosts:
          - "squid4"
          - "squid5"
          - "squid6"

  # NVMe over Fabrics: 고성능 블록 스토리지 사용 시 필요
  nvmeof:
    - name: "nvmeof.default"
      pool: "nvme_pool"
      placement:
        hosts:
          - "squid5"
          - "squid6"